# Generated by Django 4.1.2 on 2022-10-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="superhost",
            new_name="super_host",
        ),
    ]
