# Generated by Django 4.1.2 on 2022-10-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_roomtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ManyToManyField(blank=True, to="rooms.roomtype"),
        ),
    ]
