# Generated by Django 4.1.2 on 2022-10-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_alter_amenity_options_alter_facility_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="houserules",
            new_name="house_rules",
        ),
    ]
