# Generated by Django 4.1.2 on 2022-10-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="paticipants",
            new_name="participants",
        ),
    ]
